package com.xmgl.kan.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.xmgl.kan.db.entity.Urls;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "URLS".
*/
public class UrlsDao extends AbstractDao<Urls, Long> {

    public static final String TABLENAME = "URLS";

    /**
     * Properties of entity Urls.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Username = new Property(1, String.class, "username", false, "USERNAME");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Orgno = new Property(3, String.class, "orgno", false, "ORGNO");
        public final static Property Orgname = new Property(4, String.class, "orgname", false, "ORGNAME");
        public final static Property Url = new Property(5, String.class, "url", false, "URL");
        public final static Property Intvalue = new Property(6, Integer.class, "intvalue", false, "INTVALUE");
        public final static Property Urlenable = new Property(7, Boolean.class, "urlenable", false, "URLENABLE");
    };

    private DaoSession daoSession;


    public UrlsDao(DaoConfig config) {
        super(config);
    }
    
    public UrlsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"URLS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USERNAME\" TEXT," + // 1: username
                "\"NAME\" TEXT," + // 2: name
                "\"ORGNO\" TEXT," + // 3: orgno
                "\"ORGNAME\" TEXT," + // 4: orgname
                "\"URL\" TEXT," + // 5: url
                "\"INTVALUE\" INTEGER," + // 6: intvalue
                "\"URLENABLE\" INTEGER);"); // 7: urlenable
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"URLS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Urls entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String orgno = entity.getOrgno();
        if (orgno != null) {
            stmt.bindString(4, orgno);
        }
 
        String orgname = entity.getOrgname();
        if (orgname != null) {
            stmt.bindString(5, orgname);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
 
        Integer intvalue = entity.getIntvalue();
        if (intvalue != null) {
            stmt.bindLong(7, intvalue);
        }
 
        Boolean urlenable = entity.getUrlenable();
        if (urlenable != null) {
            stmt.bindLong(8, urlenable ? 1L: 0L);
        }
    }

    @Override
    protected void attachEntity(Urls entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Urls readEntity(Cursor cursor, int offset) {
        Urls entity = new Urls( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // username
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // orgno
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // orgname
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // url
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // intvalue
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0 // urlenable
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Urls entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUsername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOrgno(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOrgname(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIntvalue(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setUrlenable(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Urls entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Urls entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
