package com.xmgl.kan.db.entity;

import com.xmgl.kan.db.dao.DaoSession;
import com.xmgl.kan.db.dao.UrlParamsDao;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "URL_PARAMS".
 */
public class UrlParams {

    private Long id;
    private String userName;
    private Long urlid;
    private String name;
    private String type;
    private Boolean required;
    private String rowid;
    private String content;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient UrlParamsDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UrlParams() {
    }

    public UrlParams(Long id) {
        this.id = id;
    }

    public UrlParams(Long id, String userName, Long urlid, String name, String type, Boolean required, String rowid, String content) {
        this.id = id;
        this.userName = userName;
        this.urlid = urlid;
        this.name = name;
        this.type = type;
        this.required = required;
        this.rowid = rowid;
        this.content = content;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getUrlParamsDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Long getUrlid() {
        return urlid;
    }

    public void setUrlid(Long urlid) {
        this.urlid = urlid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getRequired() {
        return required;
    }

    public void setRequired(Boolean required) {
        this.required = required;
    }

    public String getRowid() {
        return rowid;
    }

    public void setRowid(String rowid) {
        this.rowid = rowid;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
