package com.xmgl.kan.db.entity;

import com.xmgl.kan.db.dao.DaoSession;
import com.xmgl.kan.db.dao.UrlsDao;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "URLS".
 */
public class Urls {

    private Long id;
    private String username;
    private String name;
    private String orgno;
    private String orgname;
    private String url;
    private Integer intvalue;
    private Boolean urlenable;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient UrlsDao myDao;


    // KEEP FIELDS - put your custom fields here
    private List<UrlParams> paramlist;
    // KEEP FIELDS END

    public Urls() {
    }

    public Urls(Long id) {
        this.id = id;
    }

    public Urls(Long id, String username, String name, String orgno, String orgname, String url, Integer intvalue, Boolean urlenable) {
        this.id = id;
        this.username = username;
        this.name = name;
        this.orgno = orgno;
        this.orgname = orgname;
        this.url = url;
        this.intvalue = intvalue;
        this.urlenable = urlenable;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getUrlsDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOrgno() {
        return orgno;
    }

    public void setOrgno(String orgno) {
        this.orgno = orgno;
    }

    public String getOrgname() {
        return orgname;
    }

    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getIntvalue() {
        return intvalue;
    }

    public void setIntvalue(Integer intvalue) {
        this.intvalue = intvalue;
    }

    public Boolean getUrlenable() {
        return urlenable;
    }

    public void setUrlenable(Boolean urlenable) {
        this.urlenable = urlenable;
    }

    public List<UrlParams> getParamlist() {
        return paramlist;
    }

    public void setParamlist(List<UrlParams> paramlist) {
        this.paramlist = paramlist;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }


    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }


    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
